### ISSUE TITLE
New libxml2 release is upcoming

### ISSUE THREAD

**Issue by scoder** [mhils/libxml2-win-binaries#13]
According to
https://mail.gnome.org/archives/xml/2017-August/msg00003.html
a new libxml2 release is coming up soon, which will hopefully solve some issues with the latest two releases. I'd like to include it in the binaries for the next lxml release, so would be good to quickly get the libraries built when they are out.

**Comment by mhils** [comment]
The build process currently depends on https://github.com/winlibs/libxml2, so as soon as that's updated, I can look into it. I have given you commit rights in case you want to push this faster. :-)

**Comment by scoder** [comment]
winlibs have been updated, both for libxml2 and libxslt.

**Comment by scoder** [comment]
BTW, zlib has also been updated in winlibs. And there are also changes in the libiconv repo, now based on 1.15. Probably worth updating all, now that we're at it.

**Comment by scoder** [comment]
I pushed the update, but then found out that I also have to update the upload filenames :) Having those extracted automatically from the checkouts would be nice...

**Comment by scoder** [comment]
The build with older compilers failed, it seems. Don't know what else is there to do. Could you take over?

**Comment by mhils** [comment]
https://github.com/winlibs/libiconv/commit/8cede143047edef1e8138d66bae3ca69308d1786 removed the MSVC9 solution for libiconv. We can

 1. not care about updating Python 2.7 binaries
 2. use iconv 1.14 for all builds (I have not checked if there are other issues other than iconv)
 3. only use iconv 1.14 for the Python 2.7 binaries (we can hopefully just `git checkout` in the build script)
 4. try to create a new MSVC9 solution file

Thoughts?

**Comment by scoder** [comment]
Use 1.14. Keep it simple.

Will the "latest" URLs update automatically once the build is through?

**Comment by scoder** [comment]
Worked. Thanks!

**Comment by mhils** [comment]
Great - fwiw, "latest" URLs are not updated automatically but the binaries need to be moved manually from AppVeyor's artifact tab to GitHub's releases tab. :)

That being said, we have never included the vs2008 binaries there, so I guess they are just unused right now and can probably be removed at some point.

**Comment by scoder** [comment]
> That being said, we have never included the vs2008 binaries there, so I guess they are just unused right now and can probably be removed at some point.

Would they be usable by the Py2.7 builds? I'd like to get those working. They are still using the hugely outdated zlatkovic binaries.

**Comment by mhils** [comment]
I guess so - this was introduced by @TBBle in https://github.com/mhils/libxml2-win-binaries/pull/9, it's probably enough to upload them as part of the latest release and then use them in buildlibxml.py

For the record, the VS2008 x64 build shows errors on appveyor, but still seems to go through.

**Comment by scoder** [comment]
Build seems quite happy:
https://ci.appveyor.com/project/St/lxml/build/1.0.25
Even the VS10 build in Py3.4 seems to produce "something".

Note that I now parse the releases page and extract the latest release. As long as you keep up the release tag naming by Y.M.D date, we won't need the "latest" fake release anymore.

**Comment by mhils** [comment]
Awesome, that's great to hear! :tada:

**Comment by TBBle** [comment]
https://github.com/mhils/libxml2-win-binaries/issues/13#issuecomment-330340297 describes what I intended to follow up with after #9 was merged, but I must have forgotten while waiting for the libxml2 builds to be published. I'd tested that workflow locally at the time.
