### ISSUE TITLE
Require DLL version

### ISSUE THREAD

**Issue by ccpaging** [mhils/libxml2-win-binaries#14]

**Comment by scoder** [comment]
Could you please clarify what this is about?

**Comment by ccpaging** [comment]
I have built dll version based this project by VC2003 compiler.
VC2003 is the lastest version support /ML. The DLLs has no msvcrt depends.
Add the patch for libiconv 1.15 and let Makefile.msvc worked again.

**Comment by ccpaging** [comment]
Why need DLL version? I create a small tools to convert html to markdown. It only 8k bytes as shared, but more than 1M bytes as static.

**Comment by scoder** [comment]
Did you look at https://github.com/winlibs ?
